# Generated by Django 3.2.7 on 2022-06-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_created_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='profil.png', upload_to='user/'),
        ),
    ]
